# Generated by Django 4.2 on 2023-05-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='com_listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='com_listing', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
