# Generated by Django 4.2 on 2023-05-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comments_com_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comentTime',
            new_name='commentTime',
        ),
    ]
